### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by lonacryt** [1440-2b2t/Pyro-Client#8]
Trojan

**Comment by Whop42** [comment]
yes

**Comment by d524342423** [comment]
Please leave source to claim this also ive looked a while back at the strings in virus total there isn't 0 trojan you can also decompile and look at the source 0 token or cord or any other logger besides github would've removed this if it was a trojan or a logger it would've been gone months ago it's safe a bunch of people use it this isn't the one by crystalinq and there ain't no need to worry if you want you can use virus total and look at the strings it won't say anything malicious there so if you find something please leave the source here for others to see if not don't run around saying trojan or token logger because it aint.

**Comment by 1440-2b2t** [comment]
YALL REALLY THINK ITS A TOKEN LOGGER BECAUSE ITS HIGHLY OBFUSCATED THE COPE THO

**Comment by d524342423** [comment]
> YALL REALLY THINK ITS A TOKEN LOGGER BECAUSE ITS HIGHLY OBFUSCATED THE COPE THO

Dude fr I've deobfuscated it nothing there that's dangerous I mean honesty they need to get some proof

**Comment by d524342423** [comment]
Reccomend to them using virus total it flags and shows the strings but nothing malicious

**Comment by 1440-2b2t** [comment]
> > YALL REALLY THINK ITS A TOKEN LOGGER BECAUSE ITS HIGHLY OBFUSCATED THE COPE THO
> 
> Dude fr I've deobfuscated it nothing there that's dangerous I mean honesty they need to get some proof 

Couldn't agree any more
